timeout: 3600s # Cache misses are slow to rebuild
steps:
  - id: "Load cache"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
    - "-c"
    - |
      source .ci/ci-cache.sh
      load-cache

  - id: "Build dependencies"
    waitFor:
    - "Load cache"
    name: "haskell:8.6.3"
    entrypoint: bash
    args:
    - "-c"
    - |
      cabal v2-update
      cabal v2-install -j stylish-haskell hlint
      cabal v2-build -j --enable-tests -fwith-e2e-tests --only-dependencies all

  - id: "Save cache"
    waitFor:
    - "Build dependencies"
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
    - "-c"
    - |
      source .ci/ci-cache.sh
      save-cache

  - id: "Start IPFS daemon"
    waitFor:
    - "Load cache"
    name: "gcr.io/cloud-builders/docker"
    args:
    - run
    - "--name=ipfs-test-network"
    - "--detach"
    - "--publish=5001:5001"
    - "--network=cloudbuild"
    - "eu.gcr.io/opensourcecoin/ipfs-test-network"

  - id: "Format (haskell)"
    waitFor:
    - "Save cache"
    name: "haskell:8.6.3"
    args:
    - "./.ci/check-haskell-format.sh"

  - id: "Lint (hlint)"
    waitFor:
    - "Save cache"
    name: "haskell:8.6.3"
    args:
    - "/builder/home/.cabal/bin/hlint"
    - "."

  - id: "Build and Test"
    waitFor:
    - "Save cache"
    name: "haskell:8.6.3"
    entrypoint: bash
    args:
    - "-c"
    - |
      cabal v2-configure --enable-tests
      cabal v2-build -j all
      cabal v2-test -j all

  - id: "E2E Tests"
    waitFor:
    - "Save cache"
    - "Start IPFS daemon"
    name: "haskell:8.6.3"
    env:
    - "IPFS_API_URL=http://ipfs-test-network:5001"
    args:
    - "./.ci/e2e.sh"
