jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack:
        BUILD: stack
    maxParallel: 6
  steps:
  - bash: |
      set -xeuo pipefail

      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/

      stack setup
      stack --install-ghc test
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: "${{parameters.os}}: Setup + Build + Test"
